#!/usr/bin/env bash

category=`cat data.json | jq 'keys[]' | tr -d \" | fzf`
item=`cat data.json | jq ".\"$category\" | keys[]" | tr -d \" | fzf`
cat data.json | jq ".\"$category\".\"$item\"" | tr -d \"
